// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Dragonfire.Outbox.EntityFrameworkCore;

#nullable disable

namespace Dragonfire.Outbox.SampleApp.Migrations.OutboxDb
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260415000001_ImproveIndexes")]
    partial class ImproveIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
